# Generated by Django 2.1.1 on 2018-10-03 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=20, unique=True)),
                ('parse', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=False, verbose_name='aktif?')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Provider Telekomunikasi',
            },
        ),
        migrations.CreateModel(
            name='PrefixNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(help_text='Nomor prefix operator', max_length=4, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulsa.Operator')),
            ],
            options={
                'verbose_name_plural': 'Prefix',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.PositiveSmallIntegerField(choices=[(1, 'PULSA'), (2, 'DATA')], default=1, verbose_name='tipe')),
                ('product_code', models.CharField(max_length=12, unique=True, verbose_name='kode')),
                ('product_name', models.CharField(blank=True, help_text='Nama produk website', max_length=200, verbose_name='Produk')),
                ('nominal', models.PositiveIntegerField(verbose_name='nilai nominal')),
                ('price', models.PositiveIntegerField(verbose_name='harga')),
                ('title', models.CharField(help_text='Nama produk pada aplikasi / telegram', max_length=200, verbose_name='title app')),
                ('description', models.TextField(blank=True, help_text='Deskripsi produk', max_length=500, verbose_name='deskripsi app')),
                ('additional_info', models.TextField(blank=True, help_text='* Opsional', max_length=500, verbose_name='info pemesanan')),
                ('is_active', models.BooleanField(default=False, verbose_name='aktif?')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulsa.Operator', verbose_name='Pilih operator')),
            ],
            options={
                'verbose_name_plural': 'Produk Data Pulsa',
                'ordering': ['operator', 'product_type', 'nominal'],
            },
        ),
        migrations.CreateModel(
            name='ResponseTrx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_produk', models.CharField(max_length=200)),
                ('waktu', models.CharField(max_length=200)),
                ('no_hp', models.CharField(max_length=200)),
                ('sn', models.CharField(max_length=200)),
                ('ref1', models.CharField(max_length=200)),
                ('ref2', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('ket', models.CharField(max_length=200)),
                ('saldo_terpotong', models.PositiveIntegerField(default=0)),
                ('sisa_saldo', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Kode produk layanan H2H', max_length=12, verbose_name='kode')),
                ('product_name', models.CharField(blank=True, max_length=200, verbose_name='nama produk')),
                ('price', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Rajabiller Pulsa',
            },
        ),
        migrations.CreateModel(
            name='StatusTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN', 'IN PROCESS'), ('PE', 'PENDING'), ('SS', 'SUCCESS'), ('FA', 'FAILED'), ('CA', 'CANCELED')], default='IN', max_length=2)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'get_latest_by': ['timestamp'],
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trx_code', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=18)),
                ('price', models.PositiveIntegerField(default=0)),
                ('closed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyerpulsa', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulsa.Product')),
                ('record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salepulsa', to='sale.Sale')),
            ],
        ),
        migrations.AddField(
            model_name='statustransaction',
            name='trx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulsa.Transaction'),
        ),
        migrations.AddField(
            model_name='responsetrx',
            name='trx',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pulsa.Transaction'),
        ),
        migrations.AddField(
            model_name='product',
            name='server',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pulsa.Server'),
        ),
    ]
