# Generated by Django 2.1.1 on 2018-12-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulsa', '0003_auto_20181106_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='t_notive',
            field=models.BooleanField(default=False),
        ),
    ]
