# Generated by Django 2.1.1 on 2018-12-11 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulsa', '0005_auto_20181205_1648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responsetrx',
            options={'ordering': ['-timestamp']},
        ),
    ]
