# Generated by Django 2.1.1 on 2018-10-09 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('status', models.BooleanField(default=False)),
                ('keterangan', models.CharField(max_length=200)),
            ],
        ),
    ]
