# Generated by Django 2.1.1 on 2018-10-09 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_messagepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagepost',
            name='sent_message_now',
            field=models.BooleanField(default=False),
        ),
    ]
