# Generated by Django 2.1.1 on 2018-10-17 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_messagepost_sent_message_now'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['email'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
