# Generated by Django 2.1.1 on 2018-10-03 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=20, unique=True, verbose_name='Provider')),
                ('parse', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=False, verbose_name='aktif?')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Provider Listrik',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=10, unique=True, verbose_name='kode')),
                ('product_name', models.CharField(help_text='Nama produk on website', max_length=100, verbose_name='produk')),
                ('nominal', models.PositiveIntegerField(default=0)),
                ('price', models.PositiveIntegerField(verbose_name='harga')),
                ('title', models.CharField(help_text='Nama produk on telegram / apps', max_length=200, verbose_name='title app')),
                ('description', models.TextField(blank=True, help_text='Deskripsi penjelasan produk', max_length=500, verbose_name='Deskripsi')),
                ('additional_info', models.TextField(blank=True, help_text='Deskripsi tambahan produk', max_length=500, verbose_name='Optional')),
                ('is_active', models.BooleanField(default=False, verbose_name='aktif?')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listrik.Operator', verbose_name='provider')),
            ],
            options={
                'verbose_name_plural': 'Produk Token Listrik',
                'ordering': ['nominal'],
            },
        ),
        migrations.CreateModel(
            name='ResponseTrx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_produk', models.CharField(blank=True, max_length=50)),
                ('waktu', models.CharField(blank=True, max_length=50)),
                ('idpel1', models.CharField(blank=True, max_length=50)),
                ('idpel2', models.CharField(blank=True, max_length=50)),
                ('idpel3', models.CharField(blank=True, max_length=50)),
                ('nama_pelanggan', models.CharField(blank=True, max_length=50)),
                ('periode', models.CharField(blank=True, max_length=50)),
                ('nominal', models.PositiveIntegerField(default=0)),
                ('admin', models.PositiveIntegerField(default=0)),
                ('ref1', models.CharField(blank=True, max_length=50)),
                ('ref2', models.CharField(blank=True, max_length=50)),
                ('ref3', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('ket', models.CharField(blank=True, max_length=200)),
                ('saldo_terpotong', models.PositiveIntegerField(default=0)),
                ('sisa_saldo', models.PositiveIntegerField(default=0)),
                ('url_struk', models.CharField(blank=True, max_length=200)),
                ('datail', models.TextField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN', 'IN PROCESS'), ('PE', 'PENDING'), ('SS', 'SUCCESS'), ('FA', 'FAILED'), ('CA', 'CANCELED')], default='IN', max_length=2)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'get_latest_by': ['timestamp'],
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trx_code', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=18)),
                ('price', models.PositiveIntegerField(default=0)),
                ('closed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyerlistrik', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listrik.Product')),
                ('record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salelistrik', to='sale.Sale')),
            ],
        ),
        migrations.AddField(
            model_name='statustransaction',
            name='trx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listrik.Transaction'),
        ),
        migrations.AddField(
            model_name='responsetrx',
            name='trx',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='listrik.Transaction'),
        ),
    ]
