# Generated by Django 2.1.1 on 2018-10-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsetrx',
            name='ket',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='responsetrx',
            name='kode_produk',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='responsetrx',
            name='no_hp',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='responsetrx',
            name='ref1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='responsetrx',
            name='ref2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='responsetrx',
            name='sn',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='responsetrx',
            name='status',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='responsetrx',
            name='waktu',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
