# Generated by Django 2.1.1 on 2018-10-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
