# Generated by Django 2.1.1 on 2018-10-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_cash_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='noted',
            field=models.BooleanField(default=False),
        ),
    ]
