# Generated by Django 2.1.1 on 2018-11-15 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_auto_20181105_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cash',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-timestamp']},
        ),
    ]
