# Generated by Django 2.1.1 on 2018-12-06 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transport', '0005_auto_20181205_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='loading',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sourcedata',
            name='trx',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transport.Transaction'),
        ),
        migrations.AddField(
            model_name='sourcedata',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
