# Generated by Django 2.1.1 on 2018-12-06 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_auto_20181206_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourcedata',
            options={'ordering': ['-timestamp']},
        ),
    ]
