# Generated by Django 2.1.1 on 2018-12-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0007_auto_20181206_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='procesing',
            field=models.BooleanField(default=False),
        ),
    ]
